### ISSUE TITLE
django-tagging incompatible with django 1.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [acangiani/django-tagging#234]
```
usage_for_queryset doesn't work on django 1.2 as of today:

Traceback:
File "/home/django-sites/dev/CALS/env/django/core/handlers/base.py" in
get_response
  99.                     response = callback(request, *callback_args,
**callback_kwargs)
File "/home/django-sites/dev/CALS/cals/views.py" in auth_login
  1193.     l_cloud = Tag.objects.cloud_for_model(Language, steps=7,
min_count=2)
File "/usr/local/lib/python2.6/dist-packages/tagging/models.py" in
cloud_for_model
  257.                                          min_count=min_count))
File "/usr/local/lib/python2.6/dist-packages/tagging/models.py" in
usage_for_model
  147.         usage = self.usage_for_queryset(queryset, counts, min_count)
File "/usr/local/lib/python2.6/dist-packages/tagging/models.py" in
usage_for_queryset
  165.         extra_joins = ' '.join(queryset.query.get_from_clause()[0][1:])

Exception Type: AttributeError at /
Exception Value: 'Query' object has no attribute 'get_from_clause'

I have started looking for a fix.
```

Original issue reported on code.google.com by `hanne....@gmail.com` on 24 Dec 2009 at 1:02
